# acme:
#     resource: "@AcmeBundle/Controller/"
#     type:     annotation
#     prefix:   /

api:
    resource: '.'
    type: 'api_platform'

app:
    resource: '@AppBundle/Action/'
    type: 'annotation'
